name: Build Porymap

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2' # correct version?
          modules: 'qtwidgets qtqml'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Configure
        run: qmake porymap.pro

      - name: Compile
        run: make

      - name: Create ZIP archive
        run: |
          zip porymap-linux-nightly porymap

      - name: Update nightly build
        uses: eine/tip@master
        with:
          tag: nightly
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: porymap-linux-nightly.zip
